Fix nonexistent file
- sectionImageFormats is now `ApplicationDeveloperGuide/UI/MicroUI/images.rst`
- use link instead of include

Fix:
```
WARNING: Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: 'ApplicationDeveloperGuide/sectionImageFormats.rst'.
```